routes/web.php
<?php
use App\Models\Question;
use App\Models\InsuranceCompany;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\DeleteCompanyController;
use App\Http\Controllers\DeleteQuestionController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\RespondentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $index = 1;
    $companies = InsuranceCompany::orderBy("company_name",'asc')->get();
    $questions = Question::orderBy("question",'asc')->where("active",1)->get();
    return view('home',compact('companies','questions','index'));
});
Route::get('survey-success',function(){
    return view('success');
});
Route::get("admin",function(){
    return redirect("dashboard");
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('insurance-survey', SurveyController::class);
Route::resource('company', CompanyController::class);
Route::resource('question', QuestionController::class);
Route::resource('dashboard', DashboardController::class);
Route::resource('deleteCompany', DeleteCompanyController::class);
Route::resource('deleteQuestion', DeleteQuestionController::class);
Route::resource('respondents', RespondentController::class);

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\InsuranceCompany;
use Validator;
class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $index = 1;
        $companies = InsuranceCompany::orderBy("company_name","asc")->get();
        return view("pages.companies.company",compact("index","companies"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("pages.companies.addcompany");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),[
                'company_name'         =>  'required',
                'company_logo'     =>  'required|file|mimes:jpg,jpeg,png',
            ]
        );
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        $company = new InsuranceCompany();
        if($request->hasFile('company_logo')){
            $fileName = $request->company_logo->getClientOriginalName();  
            $request->company_logo->move(public_path('storage/media/company/logo'), $fileName);
            $company->company_logo = $fileName;
        }
        $company->company_name = $request->company_name;
        $company->company_short_name = $request->company_short_name;
        $company->save();
        return redirect("company")->with("success","Company created successfully !!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $index = 1;
        $company = InsuranceCompany::findOrFail($id);
        return view("pages.companies.showcompany",compact("company",'index'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = InsuranceCompany::findOrFail($id);
        return view("pages.companies.editcompany",compact("company"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = InsuranceCompany::findOrFail($id);
        $validator = Validator::make(
            $request->all(),[
                'company_name'         =>  'required',
            ]
        );
        
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        if($request->hasFile('company_logo')){
            $fileName = $request->company_logo->getClientOriginalName();  
            $request->company_logo->move(public_path('storage/media/company/logo'), $fileName);
            $company->company_logo = $fileName;
        }

        $company->company_name = $request->company_name;
        $company->company_short_name = $request->company_short_name;
        $company->save();
        return redirect("company")->with("success","Company updated successfully !!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/companies/addcompany.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card mt-4">
                <div class="card-header">
                    <h2>Add New Company</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route("company.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method("POST")
                        <div class="form-group mt-2">
                            <label for="#company-name">Company Name</label>
                            <input type="text" name="company_name" id="company-name" class="form-control" 
                            placeholder="Company Name ">
                            @if ($errors->has('company_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_name') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <label for="#company-short-name">Company Short Name(Optional)</label>
                            <input type="text" name="company_short_name" id="company-short-name" class="form-control" 
                            placeholder="Company Short Name">
                        </div>
                        <div class="form-group mt-3">
                            <label for="#company-logo">Company Logo</label>
                            <input type="file" name="company_logo" id="company-logo" class="form-control" 
                            placeholder="Company Logo">
                            @if ($errors->has('company_logo'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_logo') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <a href="{{ url("company") }}" class="btn btn-secondary">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/companies/company.blade.php
<style>
    .company-logo{
        width:30px;
        height: 30px;
        box-shadow: 2px;
        border-radius: 50px;
    }
</style>
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert">×</button>	
            </div>
        @endif
        @if ($message = Session::get('error'))
            <div class="alert alert-danger alert-block">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert">×</button>	
            </div>
        @endif
        <div class="row mt-3">
            <div class="col-md-10"><h2>Insurance Company</h2></div>
            <div class="col-md-2">
                <a href="{{ route("company.create") }}" class="btn btn-sm btn-primary float-right">
                    <i class="fa fa-plus-circle"></i> Add New Company
                </a>
            </div>
        </div>
        <hr>
        <table class="table table-striped table-hovered table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Company Name</th>
                    <th width="30%">Company Short Name</th>
                    <th>Respondent</th>
                    <th width="10%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($companies as $company)
                    <tr>
                        <td>{{ $index++ }}</td>
                        <td>
                            <img src="{{ asset("storage/media/company/logo/".$company->company_logo) }}" 
                            alt="{{ $company->company_name }} Logo" class="company-logo">
                            {{ $company->company_name }}
                        </td>
                        <td>
                            @if ($company->company_short_name == null)
                                None
                            @else
                                {{ $company->company_short_name }}
                            @endif
                        </td>
                        <td>
                            {{ count(DB::table("insurance_company_respondent")
                            ->where("insurance_company_id",$company->id)->get()) }}
                        </td>
                        <td>
                            <a href="{{ route("company.edit",$company->id) }}">
                                <i class="fas fa-pencil-alt text-success"></i>
                            </a>
                            <a href="#" data-id="{{ $company->id }}" data-name="{{ $company->company_name }}"
                            data-logo="{{ asset("/storage/media/company/logo/".$company->company_logo) }}"
                            data-status="{{ $company->active }}"
                            data-toggle="modal" data-target="#deleteCompany">
                            @if ($company->active == 1)
                                <i class="fas fa-trash-alt text-danger"></i>
                            @else
                                <i class="fa fa-ban text-warning" aria-hidden="true"></i>
                            @endif
                            </a>
                            <a href="{{ route("company.show",$company->id) }}">
                                <i class="fas fa-eye text-info"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteCompany" tabindex="-1" role="dialog" aria-labelledby="deleteCompanyLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="" method="post" id="form-delete-company">
                    @csrf
                    @method("PUT")
                    <div class="modal-header">
                    <h5 class="modal-title" id="deleteCompanyLabel">Delete Company</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body text-center">
                        <p>Are you sure want to <span class="status text-secondary"></span> 
                            <span class="company-name text-warning"></span> ?
                        </p>
                        <img class="image-logo" src="" width="20%">
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function(){
            $("#deleteCompany").on('show.bs.modal',function(event){
                var button = $(event.relatedTarget);
                var id = button.data("id");
                var name = button.data("name");
                var logo = button.data("logo");
                var status = button.data("status");
                var modal = $(this);
                var url = "{{ route('deleteCompany.update',':id') }}";
                $(".company-name").text(name);
                $(".image-logo").attr("src",logo);
                console.log(logo)
                if (status == 1) {
                    $(".status").text('activate');
                }else{
                    $(".status").text('disactivate');
                }
                $("#form-delete-company").attr("action",url.replace(":id",id));
            });
        });
    </script>
@endpush

resources/views/pages/companies/editcompany.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card mt-4">
                <div class="card-header">
                    <h2>Update Company</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route("company.update",$company->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method("PATCH")
                        <div class="form-group mt-2">
                            <label for="#company-name">Company Name</label>
                            <input type="text" name="company_name" id="company-name" class="form-control" 
                            placeholder="Company Name " value="{{ $company->company_name }}">
                            @if ($errors->has('company_name'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_name') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <label for="#company-short-name">Company Short Name(Optional)</label>
                            <input type="text" name="company_short_name" id="company-short-name" class="form-control" 
                            placeholder="Company Short Name" value="{{ $company->company_short_name }}">
                        </div>
                        <div class="form-group mt-3">
                            <label for="#company-logo">Company Logo</label>
                            <input type="file" name="company_logo" id="company-logo" class="form-control" 
                            placeholder="Company Logo">
                            @if ($errors->has('company_logo'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('company_logo') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <a href="{{ url("company") }}" class="btn btn-secondary">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/companies/showcompany.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <h1 class="mb-3 mt-3">Company Detail</h1>
            <hr>
            <div class="col-lg-4">
                <a href="{{ url('company') }}" class="btn btn-sm btn-warning mb-4">
                    <i class="fas fa-long-arrow-alt-left"></i> Back
                </a>
                <div class="card">
                    <div class="card-body text-center">
                        <img src="{{ asset('storage/media/company/logo/'.$company->company_logo) }}" 
                            alt="{{ $company->company_name }} logo" width="50%">
                        <h1>{{ $company->company_name }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <h2>Respondents Listing</h2>
                <hr>
                <table class="table table-striped table-hovered table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Respondent Name</th>
                            <th>Respondent Email</th>
                            <th>Respondent Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($company["respondent"] as $respondent)
                            <tr>
                                <td>{{ $index++ }}</td>
                                <td>
                                    {{ $respondent->fname }} 
                                    {{ $respondent->lname }}
                                </td>
                                <td>{{ $respondent->email }}</td>
                                <td>{{ $respondent->phone }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection