routes/web.php
<?php
use App\Models\Question;
use App\Models\InsuranceCompany;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\DeleteCompanyController;
use App\Http\Controllers\DeleteQuestionController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\RespondentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $index = 1;
    $companies = InsuranceCompany::orderBy("company_name",'asc')->get();
    $questions = Question::orderBy("question",'asc')->where("active",1)->get();
    return view('home',compact('companies','questions','index'));
});
Route::get('survey-success',function(){
    return view('success');
});
Route::get("admin",function(){
    return redirect("dashboard");
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('insurance-survey', SurveyController::class);
Route::resource('company', CompanyController::class);
Route::resource('question', QuestionController::class);
Route::resource('dashboard', DashboardController::class);
Route::resource('deleteCompany', DeleteCompanyController::class);
Route::resource('deleteQuestion', DeleteQuestionController::class);
Route::resource('respondents', RespondentController::class);

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;
    protected $table='questions';
    protected $primarykey='id';
    protected $fillable = [
        'question',
    ];
    
    // one question belong to many answers
    public function answers(){
        return $this->belongsToMany(Answer::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Question;
use Validator;
class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
        $this->middleware("auth");
    }
    public function index()
    {
        $index = 1;
        $questions = Question::orderBy("question","asc")->get();

        return view("pages.questions.question",compact('index','questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("pages.questions.addquestion");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),[
                'question'         =>  'required',
            ]
        );
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        $question = new Question();
        $question->question = $request->question;
        $question->save();
        return redirect("question")->with("success","Question created successfully !!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question = Question::findOrFail($id);
        return view("pages.questions.editquestion",compact("question"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(),[
                'question'         =>  'required',
            ]
        );
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        $question = Question::findOrFail($id);
        $question->question = $request->question;
        $question->save();
        return redirect("question")->with("success","Question updated successfully !!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/questions/addquestion.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card mt-4">
                <div class="card-header">
                    <h2>Add New Question</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route("question.store") }}" method="POST">
                        @csrf
                        @method("POST")
                        <div class="form-group mt-2">
                            <label for="#question">New Question</label>
                            <textarea name="question" id="question" cols="30" rows="10"
                            class="form-control" placeholder="Enter New Question"></textarea>
                            @if ($errors->has('question'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('question') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <a href="{{ url("question") }}" class="btn btn-secondary">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/questions/editquestion.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card mt-4">
                <div class="card-header">
                    <h2>Update Question</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route("question.update",$question->id) }}" method="POST">
                        @csrf
                        @method("PATCH")
                        <div class="form-group mt-2">
                            <label for="#question">Question</label>
                            <textarea name="question" id="question" cols="30" rows="10"
                            class="form-control" placeholder="Enter New Question">
                                {{ $question->question }}
                            </textarea>
                            @if ($errors->has('question'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('question') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group mt-3">
                            <a href="{{ url("question") }}" class="btn btn-secondary">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/questions/question.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container-fluid">
        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert">×</button>	
            </div>
        @endif
        @if ($message = Session::get('error'))
            <div class="alert alert-danger alert-block">
                <strong>{{ $message }}</strong>
                <button type="button" class="close" data-dismiss="alert">×</button>	
            </div>
        @endif
        <div class="row mt-3">
            <div class="col-md-10"><h2>Questions</h2></div>
            <div class="col-md-2">
                <a href="{{ route("question.create") }}" class="btn btn-sm btn-primary float-right">
                    <i class="fa fa-plus-circle"></i> Add New Question
                </a>
            </div>
        </div>
        <hr>
        <table class="table table-striped table-hovered table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Question</th>
                    <th width="10%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($questions as $question)
                    <tr>
                        <td>{{ $index++ }}</td>
                        <td>{{ $question->question }}</td>
                        <td>
                            <a href="{{ route("question.edit",$question->id) }}">
                                <i class="fas fa-pencil-alt text-success"></i>
                            </a>
                            <a href="#" data-id="{{ $question->id }}" data-question="{{ $question->question }}"
                            data-status="{{ $question->active }}"
                            data-toggle="modal" data-target="#deleteQuestion">
                            @if ($question->active == 1)
                                <i class="fas fa-trash-alt text-danger"></i>
                            @else
                                <i class="fa fa-ban text-warning" aria-hidden="true"></i>
                            @endif
                            </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteQuestion" tabindex="-1" role="dialog" 
        aria-labelledby="deleteQuestionLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="" method="post" id="form-delete-question">
                    @csrf
                    @method("PUT")
                    <div class="modal-header">
                    <h5 class="modal-title" id="deleteQuestionLabel">Delete Question</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body text-center">
                        <p>Are you sure want to <span class="status text-secondary"></span> 
                            <span class="question text-warning"></span> ?
                        </p>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function(){
            $("#deleteQuestion").on('show.bs.modal',function(event){
                var button = $(event.relatedTarget);
                var id = button.data("id");
                var question = button.data("question");
                var status = button.data("status");
                var modal = $(this);
                var url = "{{ route('deleteQuestion.update',':id') }}";
                $(".question").text(question);
                if (status == 1) {
                    $(".status").text('activate');
                }else{
                    $(".status").text('disactivate');
                }
                $("#form-delete-question").attr("action",url.replace(":id",id));
            });
        });
    </script>
@endpush